spring:
  application:
    name: nano
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

nano:
  geoip:
    ipv4-path: ${NANO_GEOIP_IPV4_PATH}
    ipv6-path: ${NANO_GEOIP_IPV6_PATH}
  permutation:
    prime: ${NANO_PERMUTATION_PRIME}
    max-limit: ${NANO_PERMUTATION_MAX_LIMIT}
    xor-mask: ${NANO_PERMUTATION_XOR_MASK}
  base62:
    dictionary: ${NANO_BASE62_DICTIONARY}
  partition:
    timezone: ${NANO_PARTITION_TIMEZONE:Asia/Kolkata}
    cron: ${NANO_PARTITION_CRON:0 0 0 * * SUN}